# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RegionDriveforN' do
    pod 'GoogleAPIClient/Core', '~> 1.0.2'
    pod 'GoogleAPIClient/Calendar', '~> 1.0.2'
    pod 'GTMAppAuth'
end

